# Project: Kalkulator
# Makefile created by Dev-C++ 5.8.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/lib" -L"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/include" -I"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/include" -I"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"Z:/Szko³a/Podstawy programowania/Dev-Cpp 5.8.0 TDM-GCC 4.8.1 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Kalkulator.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
